version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    versioning-strategy: 'increase'
    open-pull-requests-limit: 5
    groups:
      production-minor-and-patch:
        patterns:
          - '*'
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      development-minor-and-patch:
        patterns:
          - '*'
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Helsinki'
    groups:
      github-actions:
        patterns:
          - '*'
