export const defaultVotes = [
  ['Väykkä', 'Stobb', 'Laho-Hall', 'Maik Weiv'],
  ['Väykkä', 'Maik Weiv', 'Stobb', 'Laho-Hall'],
  ['Väykkä'],
  ['Stobb', 'Laho-Hall'],
  ['Väykkä'],
  ['Laho-Hall', 'Väykkä', 'Stobb', 'Maik Weiv'],
  [],
  ['Laho-Hall'],
  ['Stobb', 'Laho-Hall'],
  ['Väykkä'],
  ['Laho-Hall', 'Maik Weiv'],
  ['Väykkä', 'Stobb', 'Maik Weiv', 'Laho-Hall'],
  ['Stobb', 'Väykkä', 'Maik Weiv'],
  ['Laho-Hall', 'Maik Weiv', 'Väykkä', 'Stobb'],
  ['Stobb', 'Maik Weiv', 'Laho-Hall', 'Väykkä'],
  ['Maik Weiv', 'Väykkä', 'Laho-Hall'],
  ['Maik Weiv'],
  ['Väykkä', 'Maik Weiv', 'Stobb', 'Laho-Hall'],
  ['Laho-Hall', 'Väykkä'],
  ['Maik Weiv', 'Stobb', 'Väykkä'],
  ['Väykkä', 'Laho-Hall', 'Stobb', 'Maik Weiv'],
  ['Väykkä', 'Laho-Hall'],
  ['Väykkä', 'Maik Weiv'],
  ['Väykkä'],
  [],
  ['Väykkä', 'Stobb', 'Maik Weiv'],
  ['Stobb', 'Laho-Hall', 'Maik Weiv', 'Väykkä'],
  ['Maik Weiv', 'Stobb', 'Laho-Hall'],
  ['Laho-Hall', 'Väykkä'],
  ['Laho-Hall', 'Maik Weiv', 'Väykkä'],
  ['Väykkä', 'Laho-Hall', 'Stobb', 'Maik Weiv'],
  ['Stobb'],
  ['Maik Weiv'],
  ['Laho-Hall', 'Stobb'],
  ['Laho-Hall'],
  ['Laho-Hall'],
  ['Laho-Hall', 'Maik Weiv', 'Stobb'],
  [],
  ['Stobb', 'Maik Weiv', 'Väykkä'],
  ['Stobb', 'Maik Weiv', 'Laho-Hall'],
  ['Laho-Hall', 'Maik Weiv', 'Väykkä'],
  ['Stobb', 'Väykkä', 'Maik Weiv', 'Laho-Hall'],
  ['Stobb'],
  ['Väykkä'],
  ['Väykkä', 'Stobb', 'Maik Weiv'],
  ['Maik Weiv', 'Laho-Hall', 'Stobb'],
  ['Laho-Hall', 'Väykkä', 'Stobb', 'Maik Weiv'],
  ['Maik Weiv', 'Stobb', 'Laho-Hall', 'Väykkä'],
  ['Stobb', 'Väykkä', 'Maik Weiv', 'Laho-Hall'],
  ['Stobb', 'Väykkä'],
];
